// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DemoLynn.Models;

public partial class Business
{
    public Guid Id { get; set; }

    public string Name { get; set; }
}