// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using DemoLynn.Models.InternalModel;
using Microsoft.EntityFrameworkCore;

namespace DemoLynn.Models;

public partial class DEMOLYNNContext : DbContext
{
    public DEMOLYNNContext()
    {
    }

    public DEMOLYNNContext(DbContextOptions<DEMOLYNNContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(ConnectionStrings.Provider.GetValue<string>("DemoLynn"));            
        }
    }

    public virtual DbSet<Business> Businesses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Business>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Name }).HasName("BUSINESS_PK");

            entity.ToTable("BUSINESS");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("NAME");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}